### ISSUE TITLE
ORA-06561 @ DBMS_SQL

### ISSUE THREAD

**Issue by 100apm** [jonheller1/method4#2]
Hi，i installed method4，but when i tested “select * from table(method4.query('select * from dual')) ”   
it appears as below：
ORA-06561:  Given statement is not supported by package DBMS_SQL
ORA-06512: at "SYS.DBMS_SQL", line 1199
ORA-06512: at "ADP.METHOD4_OT", line 19
ORA-06512: at line 4

looks like METHOD4_OT didnt get the input sql "SELECT * FROM DUAL", could you please help figure it out？

**Comment by jonheller1** [comment]
This error may be caused by the parameter CURSOR_SHARING being set to FORCE. These ODCI table functions are different than regular functions - ODCITableDescribe only works with literals, not bind variables. What is the value for this parameter: `select value from v$parameter where name = 'cursor_sharing';`

I can reproduce this issue on my machine with this code:
```
alter session set cursor_sharing=force;
alter system flush shared_pool;
select * from table(method4.query('select * from dual'));
```

Ideally, every database should have that parameter set to EXACT. Obviously, that's not always possible though, and chances are your DBAs won't want to change any parameters. As a workaround, can you try this query:
`select /*+ cursor_sharing_exact */ * from table(method4.query('select * from dual'));`

Other than changing that parameter or using a hint, I'm not sure if there's a better solution. But let me know if that hint works for you; I can at least add some error checking so if this happens again the error message will explain what's going on.

Thanks for reporting this issue!

**Comment by 100apm** [comment]
the hint works! Great thanks!!
To be metioned ,when i try the query with the hint, there is the exception who told me i need to install "DBMS_SHARED_POOL" first.
Thanks again!

SQL> select /*+ cursor_sharing_exact */ * from table(method4.query('select * from dual'));

D
-
X

SQL> select  * from table(method4.query('select * from dual'));
select  * from table(method4.query('select * from dual'))
*
ERROR at line 1:
ORA-06561: given statement is not supported by package DBMS_SQL
ORA-06512: at "SYS.DBMS_SQL", line 1199
ORA-06512: at "ADP.METHOD4_OT", line 19
ORA-06512: at line 4

**Comment by 100apm** [comment]
check if DBMS_SHARED_POOL is installed
use hint /*+ cursor_sharing_exact */

**Comment by jonheller1** [comment]
@100apm In version 2.2.3 I added better error handling so the next person that encounters this problem will know how to work around it.

In a future version, I plan to add checks and more information for the required privileges.

Thanks again for reporting this issue.
