### ISSUE TITLE
bug on the code

### ISSUE THREAD

**Issue by leo-cheang-tfs** [jonheller1/method4#4]
A `"` double quote as a column name will break the program.
```
 SELECT * FROM TABLE(METHOD4.PIVOT(q'[ 
    SELECT 'A"' COL1, 2 COL2 FROM DUAL UNION ALL
    SELECT 'B', 3 FROM DUAL
 ]')) 
```

**Comment by jonheller1** [comment]
@leo-cheang-tfs Thank you for bringing this bug to my attention, and I apologize for taking so long to reply.

A double quote will never work here because of Oracle's column naming limitation - see https://stackoverflow.com/q/14500872/409172 for some details.

Would you prefer that I raise an error and warn the user, or should I silently translate the character to something else?

I'm leaning towards raising an error message like this: "Per the Oracle documentation, "neither quoted nor nonquoted identifiers can contain double quotation marks". You may want to add a REPLACE function to the second-to-last column in your SQL statement to prevent values with double quotations marks."

Alternatively, I could automatically replace the double quotation mark with something else. Perhaps a different character that is similar to the double quotation mark. For example, one of these: https://util.unicode.org/UnicodeJsps/confusables.jsp?a=%22&r=None. But that could lead to other issue - maybe the user doesn't want UTF characters, or maybe it's not good to subtly replace a value and trick the user into thinking the new character is a real double quote.

What do you think?

**Comment by jonheller1** [comment]
@leo-cheang-tfs I changed the code to automatically convert double quotation marks to underscores. It's not a perfect solution, because the double quotation marks may collide with other characters. Ideally, I would have liked to use an optional parameter for the replacement character, but unfortunately an Oracle bug prevents that from working. Sorry this change took so long, and hopefully it's good enough.
